export type ResourceLibraryCategory = "labour" | "plant" | "material" | "materials";

export type ResourceLibraryItem = {
  name: string;
  unit: string;
};

const labour: ResourceLibraryItem[] = [
  { name: "Groundworker", unit: "hour" },
  { name: "Groundworker (Skilled)", unit: "hour" },
  { name: "General Operative", unit: "hour" },
  { name: "Ganger", unit: "hour" },
  { name: "Foreman", unit: "hour" },
  { name: "Site Supervisor", unit: "hour" },
  { name: "Site Manager", unit: "day" },
  { name: "Engineer", unit: "hour" },
  { name: "Senior Engineer", unit: "hour" },
  { name: "Quantity Surveyor", unit: "hour" },
  { name: "Commercial Manager", unit: "day" },
  { name: "Slinger / Signaller", unit: "hour" },
  { name: "Banksman", unit: "hour" },
  { name: "Traffic Marshal", unit: "hour" },
  { name: "Pipelayer", unit: "hour" },
  { name: "Drainage Gang", unit: "day" },
  { name: "Bricklayer", unit: "hour" },
  { name: "Steelfixer", unit: "hour" },
  { name: "Carpenter", unit: "hour" },
  { name: "Shuttering Carpenter", unit: "hour" },
  { name: "Concrete Finisher", unit: "hour" },
  { name: "Kerb Layer", unit: "hour" },
  { name: "Pavior", unit: "hour" },
  { name: "Plant Operator", unit: "hour" },
  { name: "Excavator Operator", unit: "hour" },
  { name: "Dumper Driver", unit: "hour" },
  { name: "Roller Driver", unit: "hour" },
  { name: "Telehandler Operator", unit: "hour" },
  { name: "CPCS Labourer", unit: "hour" },
  { name: "Skilled Labourer", unit: "hour" },
  { name: "Labourer", unit: "hour" },
  { name: "Welder / Fabricator", unit: "hour" },
  { name: "Joiner", unit: "hour" },
  { name: "Electrician", unit: "hour" },
  { name: "Ground Investigation Gang", unit: "day" },
  { name: "Topographical Surveyor", unit: "day" },
  { name: "Temporary Works Coordinator", unit: "day" },
  { name: "Temporary Works Supervisor", unit: "day" },
  { name: "NRSWA Operative", unit: "hour" },
  { name: "NRSWA Supervisor", unit: "hour" },
];

const plant: ResourceLibraryItem[] = [
  { name: "0.8T Excavator", unit: "day" },
  { name: "1.5T Excavator", unit: "day" },
  { name: "3T Excavator", unit: "day" },
  { name: "5T Excavator", unit: "day" },
  { name: "8T Excavator", unit: "day" },
  { name: "13T Excavator", unit: "day" },
  { name: "14T Excavator", unit: "day" },
  { name: "20T Excavator", unit: "day" },
  { name: "21T Excavator", unit: "day" },
  { name: "25T Excavator", unit: "day" },
  { name: "35T Excavator", unit: "day" },
  { name: "Dozer", unit: "day" },
  { name: "D6 Dozer", unit: "day" },
  { name: "Loading Shovel", unit: "day" },
  { name: "Skid Steer", unit: "day" },
  { name: "6T Dumper", unit: "day" },
  { name: "9T Dumper", unit: "day" },
  { name: "Forward Tipping Dumper", unit: "day" },
  { name: "Ride-On Roller", unit: "day" },
  { name: "Pedestrian Roller", unit: "day" },
  { name: "Twin Drum Roller", unit: "day" },
  { name: "Wacker Plate", unit: "day" },
  { name: "Rammax Trench Roller", unit: "day" },
  { name: "Telehandler", unit: "day" },
  { name: "Rotating Telehandler", unit: "day" },
  { name: "Forklift", unit: "day" },
  { name: "Crane", unit: "day" },
  { name: "Mobile Crane", unit: "day" },
  { name: "Hiab", unit: "day" },
  { name: "MEWP", unit: "day" },
  { name: "Cherry Picker", unit: "day" },
  { name: "Scissor Lift", unit: "day" },
  { name: "Bowser", unit: "day" },
  { name: "Water Bowser", unit: "day" },
  { name: "Fuel Bowser", unit: "day" },
  { name: "Generator", unit: "day" },
  { name: "Welfare Unit", unit: "week" },
  { name: "Traffic Lights", unit: "week" },
  { name: "Road Sweeper", unit: "day" },
  { name: "Trencher", unit: "day" },
  { name: "Hydraulic Breaker", unit: "day" },
  { name: "Compactor", unit: "day" },
  { name: "Concrete Pump", unit: "day" },
  { name: "Line Pump", unit: "day" },
  { name: "Water Pump", unit: "day" },
  { name: "Wellpoint Pump", unit: "day" },
  { name: "Vacuum Excavator", unit: "day" },
  { name: "Jet Vac", unit: "day" },
  { name: "Grab Lorry", unit: "day" },
  { name: "Tipper Wagon", unit: "day" },
  { name: "Low Loader", unit: "day" },
];

const materials: ResourceLibraryItem[] = [
  { name: "Type 1 Sub-base", unit: "t" },
  { name: "Type 3 Sub-base", unit: "t" },
  { name: "6F2 Capping", unit: "t" },
  { name: "Pipe Bedding", unit: "t" },
  { name: "Selected Fill", unit: "m3" },
  { name: "Imported Fill", unit: "m3" },
  { name: "Concrete C16/20", unit: "m3" },
  { name: "Concrete C20/25", unit: "m3" },
  { name: "Concrete C25/30", unit: "m3" },
  { name: "Concrete C32/40", unit: "m3" },
  { name: "Concrete C40/50", unit: "m3" },
  { name: "Reinforcement", unit: "t" },
  { name: "A393 Mesh", unit: "sheet" },
  { name: "A252 Mesh", unit: "sheet" },
  { name: "Timber", unit: "m" },
  { name: "Plywood", unit: "sheet" },
  { name: "Geotextile", unit: "m2" },
  { name: "Geogrid", unit: "m2" },
  { name: "Terram", unit: "m2" },
  { name: "Membrane", unit: "m2" },
  { name: "110mm Twinwall Duct", unit: "m" },
  { name: "150mm Twinwall Duct", unit: "m" },
  { name: "225mm Twinwall Duct", unit: "m" },
  { name: "450mm Pipe", unit: "m" },
  { name: "600mm Pipe", unit: "m" },
  { name: "750mm Pipe", unit: "m" },
  { name: "900mm Pipe", unit: "m" },
  { name: "Land Drain", unit: "m" },
  { name: "Perforated Pipe", unit: "m" },
  { name: "Manhole Ring", unit: "each" },
  { name: "Cover Slab", unit: "each" },
  { name: "Frame and Cover", unit: "each" },
  { name: "Catchpit Chamber", unit: "each" },
  { name: "Road Gully", unit: "each" },
  { name: "Kerb", unit: "m" },
  { name: "Edging", unit: "m" },
  { name: "Block Paving", unit: "m2" },
  { name: "Binder Course Asphalt", unit: "t" },
  { name: "Surface Course Asphalt", unit: "t" },
  { name: "Topsoil", unit: "m3" },
  { name: "Seed Mix", unit: "kg" },
  { name: "Marker Tape", unit: "m" },
  { name: "Ducting", unit: "m" },
  { name: "Shingle", unit: "t" },
  { name: "Gabion Stone", unit: "t" },
  { name: "PCC Kerb", unit: "m" },
  { name: "Mortar", unit: "kg" },
  { name: "Sand", unit: "t" },
  { name: "Cement", unit: "bag" },
  { name: "Reinstatement Material", unit: "t" },
];

export const RESOURCE_LIBRARY = { labour, plant, material: materials, materials };

export const COMMON_IMPORT_LIBRARY = {
  labour: labour.slice(0, 10),
  plant: [
    { name: "3T Excavator", unit: "day" },
    { name: "8T Excavator", unit: "day" },
    { name: "13T Excavator", unit: "day" },
    { name: "21T Excavator", unit: "day" },
    { name: "25T Excavator", unit: "day" },
    { name: "6T Dumper", unit: "day" },
    { name: "Ride-On Roller", unit: "day" },
    { name: "Telehandler", unit: "day" },
    { name: "Generator", unit: "day" },
    { name: "Water Pump", unit: "day" },
  ],
  materials: materials.slice(0, 12),
};

export function getResourceLibrary(category: ResourceLibraryCategory): ResourceLibraryItem[] {
  return RESOURCE_LIBRARY[category] ?? [];
}
